import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";

export const metadata: Metadata = { title: "Sobre mí" };

export default function AboutPage(){return <main><div className="page-glow"/><SiteHeader />
  <section className="about-page shell"><div className="about-page-image"><img src="/projects/jorge-about.png" alt="Jorge Luis Añanguren" /></div><div className="about-page-copy"><span>JORGE LUIS AÑANGUREN</span><h1>Tecnología, operaciones y ahora <em>productos digitales.</em></h1><p>Cuento con más de 10 años de experiencia en soporte IT, infraestructura, redes y operación tecnológica. Actualmente complemento esa trayectoria construyendo proyectos de desarrollo web, automatización con IA, datos y e-commerce.</p><p>Trabajo de forma práctica: entiendo la necesidad, construyo una primera versión, pruebo, corrijo y documento. Me interesa especialmente participar en equipos remotos donde pueda combinar resolución de problemas, experiencia tecnológica y desarrollo de nuevas soluciones.</p><div className="pill-row"><b>Next.js</b><b>React</b><b>TypeScript</b><b>PostgreSQL</b><b>Neon</b><b>Supabase</b><b>Vercel</b><b>GitHub</b><b>IA</b><b>n8n</b></div><div className="about-page-actions"><Link className="primary" href="/proyectos">Ver proyectos →</Link><a className="secondary" href="/CV_Jorge_Luis_Ananguren_Remoto_2026.pdf" target="_blank" rel="noreferrer">Descargar CV ↓</a><a className="secondary" href="https://www.linkedin.com/in/jorgeluisananguren" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></section>
  <section className="career-strip shell"><article><span>10+ AÑOS</span><h2>IT, soporte e infraestructura</h2><p>Resolución de incidencias, continuidad operativa, redes, sistemas y atención a usuarios.</p></article><article><span>2024 — ACTUALIDAD</span><h2>Soluciones digitales</h2><p>Desarrollo web, proyectos propios, automatización con IA, e-commerce y productos digitales.</p></article><article><span>OBJETIVO</span><h2>Trabajo remoto global</h2><p>Desarrollo web, no-code, IA aplicada, automatización y roles tecnológicos con aprendizaje continuo.</p></article></section>
  <section className="values shell"><article><span>01</span><h2>Construir</h2><p>Prefiero aprender creando algo que pueda probarse, enseñarse y mejorarse.</p></article><article><span>02</span><h2>Automatizar</h2><p>Busco reducir tareas repetitivas y conectar herramientas para que el trabajo sea más eficiente.</p></article><article><span>03</span><h2>Iterar</h2><p>No veo un proyecto como terminado para siempre. Cada versión puede ser más clara, rápida y útil.</p></article></section>
  <SiteFooter /></main>}
